name: CI/CD for WordPress

on:
  push:
    branches: [main]

  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for services to be ready
        run: sleep 60
